openapi: "3.0.0"
info:
  title: Pastebin Plugin
  version: "1.0.0"

paths:
  /get-output:
    post:
      summary: Generate plugin output
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetOutputRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetOutputResponse"

  /process-feedback:
    post:
      summary: Process user feedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProcessFeedbackRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProcessFeedbackResponse"

components:
  schemas:
    GetOutputRequest:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"

    GetOutputResponse:
      type: object
      properties:
        id:
          type: string
        object:
          type: string
        created:
          type: integer
        model:
          type: string
        choices:
          type: array
          items:
            $ref: "#/components/schemas/Choice"

    Message:
      type: object
      properties:
        role:
          type: string
          enum: [system, user, assistant]
        content:
          type: string

    Choice:
      type: object
      properties:
        message:
          $ref: "#/components/schemas/Message"
        finish:
          type: boolean
        index:
          type: integer

    ProcessFeedbackRequest:
      type: object
      properties:
        feedback:
          type: object

    ProcessFeedbackResponse:
      type: object
      properties:
        id:
          type: string
        object:
          type: string
        action:
          type: string
        message:
          type: string

tags:
  - name: code_runner
    description: Plugins related to code running or execution
